### ISSUE TITLE
[TODO] Version Manager

### ISSUE THREAD

**Issue by SirDavidLudwig** [SirDavidLudwig/minecraft-js#1]
## Version Manager
This is one of the core modules of the library, and it needs to get done. Here is a list of everything that this module should be able to do:

- [x] List Versions:
  - [x] All available versions
  - [x] Installed versions
  - [x] Releases only
  - [x] Snapshots only
- [x] Install versions including assets and libraries
- [x] Remove installed versions
- [x] Integrity check and fix broken installations if possible
