### ISSUE TITLE
[TODO] Launcher Profiles Manager

### ISSUE THREAD

**Issue by SirDavidLudwig** [SirDavidLudwig/minecraft-js#2]
This is a core module of the library, so it needs to get done. It should be able to manage `launcher_profiles.json` in both version formats. Below is a list of everything that it should be able to do:

- [ ] Generate launcher_profiles.json
- [ ] Client Token:
  - [ ] Generate
  - [ ] Get
  - [ ] Set
- [ ] Profiles:
  - [ ] Add
  - [ ] Get:
    - [ ] All
    - [ ] Last Used
  - [ ] Modify
  - [ ] Remove
- [ ] Mojang Accounts (Authentication Database):
  - [ ] Add Account
  - [ ] Refresh Account
  - [ ] Remove Account
  - [ ] Selected Account and Profile
    - [ ] Get:
      - [ ] Account
      - [ ] Profile
    - [ ] Set
      - [ ] Account
      - [ ] Profile
- [ ] Settings:
  - [ ] enableAdvanced
  - [ ] locale
  - [ ] showMenu
  - [ ] keepLauncherOpen
  - [ ] showGameLog
  - [ ] crashAssistance,
  - [ ] enableAnalytics
